# Generated by Django 6.0.1 on 2026-01-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                (
                    "initials",
                    models.CharField(
                        help_text="Введите вашу фамилию, имя и отчество", max_length=255, verbose_name="Ф.И.О."
                    ),
                ),
                ("comment", models.TextField(help_text="Введите комментарий", verbose_name="комментарий")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "letter_subject",
                    models.CharField(help_text="Введите тему письма", max_length=255, verbose_name="Тема письма"),
                ),
                ("letter_body", models.TextField(help_text="Введите тело письма", verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attempt_time",
                    models.DateTimeField(
                        help_text="Введите дату и время попытки отправки", verbose_name="Дата и время попытки отправки"
                    ),
                ),
                ("status", models.CharField(help_text="введите статус", max_length=20, verbose_name="статус")),
                ("server_response", models.TextField(help_text="Введите ответ сервера", verbose_name="Ответ сервера")),
                ("mailing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing_app.message")),
            ],
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Введите дату и время начала отправки", verbose_name="Дата и время начала отправки"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Введите дату и время окончания отправки",
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                ("status", models.CharField(default="Создана", max_length=20, verbose_name="Статус рассылки")),
                ("recipients", models.ManyToManyField(to="mailing_app.mailingrecipient")),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing_app.message")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
